// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYBlLEXgm8BKCLKvfxhKjvdCmpPG3HoDU',
    appId: '1:110256163768:web:cd093da39cdb9d9a741d4d',
    messagingSenderId: '110256163768',
    projectId: 'mobius-5f714',
    authDomain: 'mobius-5f714.firebaseapp.com',
    storageBucket: 'mobius-5f714.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQleEHNxIv-xymBSW7J2FHbjPMioMtWEs',
    appId: '1:110256163768:android:6c2d87a2c7648df8741d4d',
    messagingSenderId: '110256163768',
    projectId: 'mobius-5f714',
    storageBucket: 'mobius-5f714.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn1t9b_CnFNv4t6-ZUnRFmpfVK9F13B_E',
    appId: '1:110256163768:ios:2559f2100f112a15741d4d',
    messagingSenderId: '110256163768',
    projectId: 'mobius-5f714',
    storageBucket: 'mobius-5f714.appspot.com',
    iosClientId: '110256163768-6isglfeogh517674gjs5o4mj4ckjg8un.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMobius',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn1t9b_CnFNv4t6-ZUnRFmpfVK9F13B_E',
    appId: '1:110256163768:ios:2559f2100f112a15741d4d',
    messagingSenderId: '110256163768',
    projectId: 'mobius-5f714',
    storageBucket: 'mobius-5f714.appspot.com',
    iosClientId: '110256163768-6isglfeogh517674gjs5o4mj4ckjg8un.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMobius',
  );
}
